name: Pages

on:
  workflow_dispatch: {}
  push:
    branches: [master]

jobs:
  publish-gh:
    name: Publish Github Pages
    runs-on: ubuntu-latest
    env: 
      PUBLIC_URL: "/weekly-draw"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install && PUBLIC_URL=/weekly-draw npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
